locale: en_EN

db:
  host: localhost
  username: root
  password: open
  dbname: project

email:
  from: info@example.com
  from_name: John Doe

secret:
  signup: 'ENTER SOME RANDOM TEXT HERE'

social:
  facebook:
      client_id:
      client_secret:
  twitter:
      consumer_key:
      consumer_secret:
  google:
      client_id:
      client_secret:
      api_key:
  linkedin:
      client_id:
      client_secret:

